import { ibmFont } from "@/app/fonts";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${ibmFont.className}`}>{children}</body>
    </html>
  );
}
